/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWewenangRouteImport } from './routes/_authenticated/wewenang'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPokjaRouteImport } from './routes/_authenticated/pokja'
import { Route as AuthenticatedKinerjaRouteImport } from './routes/_authenticated/kinerja'
import { Route as AuthenticatedKalenderRouteImport } from './routes/_authenticated/kalender'
import { Route as AuthenticatedHierarkiRouteImport } from './routes/_authenticated/hierarki'
import { Route as AuthenticatedFoldersRouteImport } from './routes/_authenticated/folders'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks.index'
import { Route as AuthenticatedTasksNewRouteImport } from './routes/_authenticated/tasks.new'
import { Route as AuthenticatedTasksTaskIdRouteImport } from './routes/_authenticated/tasks.$taskId'
import { Route as AuthenticatedReportsRekapRouteImport } from './routes/_authenticated/reports.rekap'
import { Route as ApiPublicHooksTaskRemindersRouteImport } from './routes/api/public/hooks/task-reminders'
import { Route as ApiPublicExternalTasksRouteImport } from './routes/api/public/external/tasks'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWewenangRoute = AuthenticatedWewenangRouteImport.update({
  id: '/wewenang',
  path: '/wewenang',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPokjaRoute = AuthenticatedPokjaRouteImport.update({
  id: '/pokja',
  path: '/pokja',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKinerjaRoute = AuthenticatedKinerjaRouteImport.update({
  id: '/kinerja',
  path: '/kinerja',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKalenderRoute = AuthenticatedKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHierarkiRoute = AuthenticatedHierarkiRouteImport.update({
  id: '/hierarki',
  path: '/hierarki',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFoldersRoute = AuthenticatedFoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksNewRoute = AuthenticatedTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksTaskIdRoute =
  AuthenticatedTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRekapRoute =
  AuthenticatedReportsRekapRouteImport.update({
    id: '/reports/rekap',
    path: '/reports/rekap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksTaskRemindersRoute =
  ApiPublicHooksTaskRemindersRouteImport.update({
    id: '/api/public/hooks/task-reminders',
    path: '/api/public/hooks/task-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExternalTasksRoute = ApiPublicExternalTasksRouteImport.update({
  id: '/api/public/external/tasks',
  path: '/api/public/external/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/folders': typeof AuthenticatedFoldersRoute
  '/hierarki': typeof AuthenticatedHierarkiRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/kinerja': typeof AuthenticatedKinerjaRoute
  '/pokja': typeof AuthenticatedPokjaRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/wewenang': typeof AuthenticatedWewenangRoute
  '/reports/rekap': typeof AuthenticatedReportsRekapRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/api/public/external/tasks': typeof ApiPublicExternalTasksRoute
  '/api/public/hooks/task-reminders': typeof ApiPublicHooksTaskRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/folders': typeof AuthenticatedFoldersRoute
  '/hierarki': typeof AuthenticatedHierarkiRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/kinerja': typeof AuthenticatedKinerjaRoute
  '/pokja': typeof AuthenticatedPokjaRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/wewenang': typeof AuthenticatedWewenangRoute
  '/reports/rekap': typeof AuthenticatedReportsRekapRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/api/public/external/tasks': typeof ApiPublicExternalTasksRoute
  '/api/public/hooks/task-reminders': typeof ApiPublicHooksTaskRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/folders': typeof AuthenticatedFoldersRoute
  '/_authenticated/hierarki': typeof AuthenticatedHierarkiRoute
  '/_authenticated/kalender': typeof AuthenticatedKalenderRoute
  '/_authenticated/kinerja': typeof AuthenticatedKinerjaRoute
  '/_authenticated/pokja': typeof AuthenticatedPokjaRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/wewenang': typeof AuthenticatedWewenangRoute
  '/_authenticated/reports/rekap': typeof AuthenticatedReportsRekapRoute
  '/_authenticated/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/_authenticated/tasks/new': typeof AuthenticatedTasksNewRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/api/public/external/tasks': typeof ApiPublicExternalTasksRoute
  '/api/public/hooks/task-reminders': typeof ApiPublicHooksTaskRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/activity'
    | '/api-keys'
    | '/dashboard'
    | '/documents'
    | '/folders'
    | '/hierarki'
    | '/kalender'
    | '/kinerja'
    | '/pokja'
    | '/settings'
    | '/users'
    | '/wewenang'
    | '/reports/rekap'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/tasks/'
    | '/api/public/external/tasks'
    | '/api/public/hooks/task-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/activity'
    | '/api-keys'
    | '/dashboard'
    | '/documents'
    | '/folders'
    | '/hierarki'
    | '/kalender'
    | '/kinerja'
    | '/pokja'
    | '/settings'
    | '/users'
    | '/wewenang'
    | '/reports/rekap'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/tasks'
    | '/api/public/external/tasks'
    | '/api/public/hooks/task-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/activity'
    | '/_authenticated/api-keys'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/folders'
    | '/_authenticated/hierarki'
    | '/_authenticated/kalender'
    | '/_authenticated/kinerja'
    | '/_authenticated/pokja'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/wewenang'
    | '/_authenticated/reports/rekap'
    | '/_authenticated/tasks/$taskId'
    | '/_authenticated/tasks/new'
    | '/_authenticated/tasks/'
    | '/api/public/external/tasks'
    | '/api/public/hooks/task-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicExternalTasksRoute: typeof ApiPublicExternalTasksRoute
  ApiPublicHooksTaskRemindersRoute: typeof ApiPublicHooksTaskRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wewenang': {
      id: '/_authenticated/wewenang'
      path: '/wewenang'
      fullPath: '/wewenang'
      preLoaderRoute: typeof AuthenticatedWewenangRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pokja': {
      id: '/_authenticated/pokja'
      path: '/pokja'
      fullPath: '/pokja'
      preLoaderRoute: typeof AuthenticatedPokjaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kinerja': {
      id: '/_authenticated/kinerja'
      path: '/kinerja'
      fullPath: '/kinerja'
      preLoaderRoute: typeof AuthenticatedKinerjaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kalender': {
      id: '/_authenticated/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AuthenticatedKalenderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hierarki': {
      id: '/_authenticated/hierarki'
      path: '/hierarki'
      fullPath: '/hierarki'
      preLoaderRoute: typeof AuthenticatedHierarkiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/folders': {
      id: '/_authenticated/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof AuthenticatedFoldersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/new': {
      id: '/_authenticated/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthenticatedTasksNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/$taskId': {
      id: '/_authenticated/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/rekap': {
      id: '/_authenticated/reports/rekap'
      path: '/reports/rekap'
      fullPath: '/reports/rekap'
      preLoaderRoute: typeof AuthenticatedReportsRekapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/task-reminders': {
      id: '/api/public/hooks/task-reminders'
      path: '/api/public/hooks/task-reminders'
      fullPath: '/api/public/hooks/task-reminders'
      preLoaderRoute: typeof ApiPublicHooksTaskRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/external/tasks': {
      id: '/api/public/external/tasks'
      path: '/api/public/external/tasks'
      fullPath: '/api/public/external/tasks'
      preLoaderRoute: typeof ApiPublicExternalTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFoldersRoute: typeof AuthenticatedFoldersRoute
  AuthenticatedHierarkiRoute: typeof AuthenticatedHierarkiRoute
  AuthenticatedKalenderRoute: typeof AuthenticatedKalenderRoute
  AuthenticatedKinerjaRoute: typeof AuthenticatedKinerjaRoute
  AuthenticatedPokjaRoute: typeof AuthenticatedPokjaRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWewenangRoute: typeof AuthenticatedWewenangRoute
  AuthenticatedReportsRekapRoute: typeof AuthenticatedReportsRekapRoute
  AuthenticatedTasksTaskIdRoute: typeof AuthenticatedTasksTaskIdRoute
  AuthenticatedTasksNewRoute: typeof AuthenticatedTasksNewRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFoldersRoute: AuthenticatedFoldersRoute,
  AuthenticatedHierarkiRoute: AuthenticatedHierarkiRoute,
  AuthenticatedKalenderRoute: AuthenticatedKalenderRoute,
  AuthenticatedKinerjaRoute: AuthenticatedKinerjaRoute,
  AuthenticatedPokjaRoute: AuthenticatedPokjaRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWewenangRoute: AuthenticatedWewenangRoute,
  AuthenticatedReportsRekapRoute: AuthenticatedReportsRekapRoute,
  AuthenticatedTasksTaskIdRoute: AuthenticatedTasksTaskIdRoute,
  AuthenticatedTasksNewRoute: AuthenticatedTasksNewRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicExternalTasksRoute: ApiPublicExternalTasksRoute,
  ApiPublicHooksTaskRemindersRoute: ApiPublicHooksTaskRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
